### ISSUE TITLE
_regex_core.error: unterminated character set at position 91

### ISSUE THREAD

**Issue by kercos** [berkmancenter/mediacloud-sentence-splitter#2]
Hi, great work!

I'm having a conflict when using both spacy and sentence_splitter.

The following code:
```
import spacy
from sentence_splitter import SentenceSplitter

nlp = spacy.load('en_core_web_sm')
doc = nlp("This is a sample sentence.")

splitter = SentenceSplitter(language='en')
splitter.split("This is a sample sentence.")
```
gives the following error:

```
Traceback (most recent call last):
  File "src/bug.py", line 14, in <module>
    splitter.split("This is a sample sentence.")
  File "env/lib/python3.7/site-packages/sentence_splitter/__init__.py", line 98, in split
    flags=regex.UNICODE
  File "env/lib/python3.7/site-packages/regex.py", line 275, in sub
    return _compile(pattern, flags, kwargs).sub(repl, string, count, pos,
  File "env/lib/python3.7/site-packages/regex.py", line 507, in _compile
    caught_exception.pos)
_regex_core.error: unterminated character set at position 91
```

**Comment by kercos** [comment]
Hi @pypt, by any chance did you have time to look into this?

**Comment by ruilinch** [comment]
Had similar issue. 
Why are you using these two packages together? I was trying to do a performance comparison, because spaCy is too slow if I am only interested at splitting sentences. 
I did comparison between sentence_splitter, spaCy, NLTK and coreNLP, and the conclusion is I might as well use NLTK if not spaCy... It turns out, spaCy outperforms all these packages substantially when using the text I have which are online reviews. 
I am not sure. What is the advantage of this package? Just out of curiosity. No offense to the authors.

**Comment by pypt** [comment]
Hey @kercos, sorry for a late reply, busy times on my end!

I have no proof, but I think spaCy messes with `regex` library's internals in some way, esp. given that they have pinned a specific `regex` version in their `requirements.txt`.

In a recent https://github.com/explosion/spaCy/pull/3218 PR (merged to `develop`) they got rid of `regex` dependency altogether, so I'd suggest that you try out installing that. Nightly from https://github.com/explosion/spaCy/tree/develop works for me, so I'd suggest that you try it out too!

Feel free to reopen the issue if you still encounter this issue.

**Comment by svlandeg** [comment]
> 
> I have no proof, but I think spaCy messes with `regex` library's internals in some way, esp. given that they have pinned a specific `regex` version in their `requirements.txt`.

Yep, it used to be so that spaCy globally changes the `regex` settings: https://github.com/svlandeg/spaCy/blob/master/spacy/lang/char_classes.py#L6

But indeed on `develop`, the `regex` library was removed entirely.

**Comment by kercos** [comment]
Thanks @pypt and @svlandeg for looking into this. 
I'll give it a try ASAP and let you know.
