### ISSUE TITLE
Are these two sources in sync?

### ISSUE THREAD

**Issue by umeshksingla** [berkmancenter/mediacloud-sentence-splitter#3]
There is another sentence splitting logic here in moses-smt/mosesdecoder repository at [this](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/ems/support/split-sentences.perl#L6) link, based on the preprocessor by Philipp Koehn and this package also claims it to be based on a heuristic algorithm by the same guy. 

Is the logic implemented for sentence splitting in this python package in sync with the other one? How do I decide which one to use?

**Comment by pypt** [comment]
Well, for one thing, one is written in Perl, another one in Python :)

As per the README, this module is a Python rewrite of Perl's [Lingua::Sentence](https://metacpan.org/pod/Lingua::Sentence) with some additions, and Lingua::Sentence is based on Koehn's logic itself.

The final choice is up to you!
