### ISSUE TITLE
unterminated character set at position 0

### ISSUE THREAD

**Issue by ms-soma57** [berkmancenter/mediacloud-sentence-splitter#4]
I am new to python and data science, I am learning how to clean up the dataset.so I tried few examples 
![image](https://user-images.githubusercontent.com/68239260/105618582-ffaeaa00-5db6-11eb-8848-bf23135749a3.png)

I am trying to make a copy of the column of presidents, I don't understand my error message

**Comment by pypt** [comment]
Sorry, your issue doesn't have much to do with this module.
